# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='名前')),
                ('comment', models.TextField(max_length=140, verbose_name='コメント')),
                ('star', models.BooleanField(verbose_name='スター')),
                ('archived', models.BooleanField(verbose_name='アーカイブ')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'ブックマーク',
                'verbose_name_plural': 'ブックマーク',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('fqdn', models.CharField(editable=False, max_length=140, verbose_name='完全修飾ドメイン名')),
                ('title', models.CharField(editable=False, max_length=140, verbose_name='タイトル')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': 'ページ',
                'verbose_name_plural': 'ページ',
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Page', verbose_name='ページ'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
