# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
